#!/bin/sh
#
# @name Germandrones Songbird foamie
#
# @type VTOL Tiltrotor
# @class VTOL
#
# @maintainer Germandrones
#
# @output MAIN1 motor 1
# @output MAIN2 motor 2
# @output MAIN3 motor 3
# @output MAIN4 motor 4
# @output MAIN5 Tiltservo Left
# @output MAIN6 Tiltsrevo Right
# @output MAIN7 spare 1 aileron right
# @output MAIN8 spare 2 aileron left
# @output AUX1 Aileron Left
# @output AUX2 Aileron Right
# @output AUX3 Tail elevator
# @output AUX4 Tail rudder
# @output AUX5 Camera Trigger
# @output AUX6 Camera Trigger
#


sh /etc/init.d/rc.vtol_defaults

if [ $AUTOCNF == yes ]
then
   param set BAT1_V_CHARGED   4.1100
   param set BAT1_V_EMPTY   3.5000
   param set BAT1_N_CELLS   6
   param set BAT_N_CELLS   6
   param set BAT1_SOURCE   1
   param set BAT_SOURCE   1
   param set BAT_A_PER_V   1.00
   param set BAT_V_DIV   15.468000
   param set BAT_V_EMPTY   3.50000
   param set BAT_V_CHARGED   4.100
   param set CAL_AIR_GAIN   1.0
   param set CBRK_IO_SAFETY   22027
   param set COM_ARM_CHK_ESCS   0
   param set COM_FLTMODE1   3
   param set COM_FLTMODE2   2
   param set COM_FLTMODE3   2
   param set COM_FLTMODE4   2
   param set COM_FLTMODE5   8
   param set COM_FLTMODE6   8
   param set COM_POWER_COUNT   1
   param set COM_PREARM_MODE   2
   param set EKF2_BARO_NOISE   15.0

   param set FW_PR_FF   1.2
   param set FW_PR_I   0.009999999776482582
   param set FW_PR_P   0.05
   param set FW_PSP_OFF   4.5
   param set FW_P_TC   0.5
   param set FW_RLL_TO_YAW_FF   1.0
   param set FW_RR_FF   0.50
   param set FW_RR_I   0.009999999776482582
   param set FW_RR_P   0.039999999105930328
   param set FW_R_LIM   50.0
   param set FW_R_RMAX   45.0
   param set FW_R_TC   0.50
   param set FW_THR_CRUISE   0.649999976158142090
   param set FW_THR_IDLE   0.079999998211860657
   param set FW_T_CLMB_MAX   7.0
   param set FW_T_HRATE_FF   0.40
   param set FW_T_HRATE_P   0.250
   param set FW_T_INTEG_GAIN   0.05
   param set FW_T_PTCH_DAMP   0.00
   param set FW_T_RLL2THR   10.0
   param set FW_T_SINK_MAX   5.00
   param set FW_T_SINK_MIN   1.0
   param set FW_T_THRO_CONST   8.0
   param set FW_T_THR_DAMP   1.00
   param set FW_T_TIME_CONST   6.500
   param set FW_T_VERT_ACC   7.00
   param set MAV_0_RATE   2000
   param set MAV_TYPE   21
   
   param set MC_AIRMODE   1
   param set MC_PITCHRATE_D   0.001
   param set MC_PITCHRATE_FF   0.00
   param set MC_PITCHRATE_I   0.009999999776482582
   param set MC_PITCHRATE_K   1.0000
   param set MC_PITCHRATE_MAX   75.0
   param set MC_PITCHRATE_P   0.10
   param set MC_PITCH_P   2.500
   param set MC_ROLLRATE_D   0.003
   param set MC_ROLLRATE_FF   0.000
   param set MC_ROLLRATE_I   0.002
   param set MC_ROLLRATE_K   1.0
   param set MC_ROLLRATE_MAX   75.00
   param set MC_ROLLRATE_P   0.20
   param set MC_ROLL_P   4.0
   param set MC_RR_INT_LIM   0.30
   param set MC_YAWRATE_D   0.00
   param set MC_YAWRATE_FF   0.00
   param set MC_YAWRATE_I   0.019999999552965164
   param set MC_YAWRATE_K   1.000
   param set MC_YAWRATE_MAX   120.000
   param set MC_YAWRATE_P   0.219999998807907104
   param set MC_YAW_P   2.0000
   param set MC_YAW_WEIGHT   0.4000
   param set MC_YR_INT_LIM   0.3000
   
   param set MIS_DIST_1WP   900.000
   param set MIS_DIST_WPS   2000.00
   param set MPC_LAND_SPEED   0.80
   param set MPC_MAN_TILT_MAX   30.0
   param set MPC_MAN_Y_MAX   200.00
   param set MPC_THR_HOVER   0.600
   param set MPC_THR_MAX   1.000
   param set MPC_THR_MIN   0.079999998211860657
   param set MPC_TILTMAX_AIR   25.000
   param set MPC_TILTMAX_LND   20.00
   param set MPC_TKO_RAMP_T   0.60
   param set MPC_TKO_SPEED   1.500
   param set MPC_VEL_MANUAL   6.00
   param set MPC_XY_CRUISE   6.00
   param set MPC_XY_P   0.699999988079071045
   param set MPC_XY_VEL_MAX   6.000
   param set MPC_YAWRAUTO_MAX   40.0
   param set MPC_Z_P   0.600000
   param set MPC_Z_VEL_MAX_DN   1.60
   param set MPC_Z_VEL_MAX_UP   2.00
   param set NAV_ACC_RAD   10.0
   param set NAV_FORCE_VT   1
   param set NAV_FW_ALTL_RAD   5.00
   param set NAV_FW_ALT_RAD   100.0
   param set NAV_LOITER_RAD   80.0
   param set NAV_MC_ALT_RAD   0.800
   
   param set PWM_AUX_DIS1   1500
   param set PWM_AUX_DIS2   1500
   param set PWM_AUX_DIS3   1500
   param set PWM_AUX_DIS4   1500
   param set PWM_AUX_MAX   2000
   param set PWM_AUX_MIN   1000
   param set PWM_MAIN_MAX5   2100
   param set PWM_MAIN_MAX6   2100
   param set PWM_MAIN_MIN5   900
   param set PWM_MAIN_MIN6   900
   param set PWM_MAX   2100   6
   param set RC_ARMSWITCH_TH   0.500
   param set RC_ASSIST_TH   0.25
   param set RC_AUTO_TH   0.75
   param set RC_MAP_ARM_SW   8
   param set RC_MAP_FLTMODE   7
   param set RC_MAP_PITCH   2
   param set RC_MAP_ROLL   1
   param set RC_MAP_THROTTLE   3
   param set RC_MAP_TRANS_SW   5
   param set RC_MAP_YAW   4
   param set RC_STAB_TH   0.50
   param set RC_TRANS_TH   -0.250
   param set RTL_CONE_ANG   45
   param set RTL_DESCEND_ALT   50.00
   param set RTL_LAND_DELAY   0.0
   param set RTL_MIN_DIST   20.00
   param set RTL_RETURN_ALT   100.00
   param set RTL_TYPE   1
   param set SDLOG_MODE   0
   param set SDLOG_PROFILE   65
   param set TRIG_INTERFACE   4
   param set TRIG_MODE   4
   param set TRIG_PINS   56
   param set VT_B_DEC_FF   0.119999997317790985
   param set VT_B_DEC_I   0.10000
   param set VT_B_TRANS_DUR   3.5000
   param set VT_B_TRANS_THR   1.00
   param set VT_DWN_PITCH_MAX   5.000
   param set VT_ELEV_MC_LOCK   0
   param set VT_FWD_THRUST_EN   1
   param set VT_FWD_THRUST_SC   1.500
   param set VT_FW_QC_P   70
   param set VT_FW_QC_R   150
   param set VT_F_TRANS_DUR   3.00
   param set VT_F_TRANS_THR   1.000
   param set VT_F_TR_OL_TM   6.00
   param set VT_IDLE_PWM_MC   1110
   param set VT_MOT_ID   1234
   param set VT_TILT_FW   1.00
   param set VT_TILT_MC   0.00
   param set VT_TILT_TRANS   0.379999995231628418
   param set VT_TRANS_MIN_TM   2.000
   param set VT_TRANS_P2_DUR   1.000
   param set VT_TRANS_TIMEOUT   6.000
   param set VT_TYPE   1
   param set WV_EN   1
   param set WV_GAIN   1.00
   param set WV_YRATE_MAX   90.00   

fi

set MIXER SBfoam
set PWM_OUT 1234
set PWM_RATE 400

set MIXER_AUX SBfoam
set PWM_AUX_OUT 1234
set PWM_AUX_RATE 50

set MAV_TYPE 21

# batt_pac on I2C
batt_pac17xx start -X -R 0.2 -r 40

gd_payload start

# /dev/ttyS0      IO debug except v4, there ttyS0 is the wifi
# /dev/ttyS1      TELEM1 flow control serial1, telemetry
# /dev/ttyS2      TELEM2 flow control serial2, payload
# /dev/ttyS3      GPS
# /dev/ttyS4      PX4IO
# /dev/ttyS5      debug console, serial5
# /dev/ttyS6      GPS2, ser4 free (was unisens)
